module.exports = {
    network: 'testSdk',
    port: 7545,
    endpoint: '127.0.0.1',
    protocol:'http://',
    zaRegistryPath: '../src/contracts/abis/ZapRegistry.json',
    contractsBuildDirectory: '../ZapContracts/build/contracts',
    contractsDirectory: '../ZapContracts/contracts',
    network_id: 5777,
    runMigrationTimeOut: 5000,
    migrationsDirectory: '../ZapContracts/migrations',
    zapTokenAbi: '../../ZapContracts/build/contracts/TheToken.json',
    zapRegistryAbi: '../../ZapContracts/build/contracts/Registry.json',
    zapArbiterAbi: '../../ZapContracts/build/contracts/Arbiter.json',
    zapRegistryStorageAbi: '../../ZapContracts/build/contracts/RegistryStorage.json',
    arbiterStorageAbi: '../../ZapContracts/build/contracts/ArbiterStorage.json',
    bondageStorageAbi: '../../ZapContracts/build/contracts/BondageStorage.json',
    zapBondageAbi:     '../../ZapContracts/build/contracts/Bondage.json',
    currentCostAbi: '../../ZapContracts/build/contracts/CurrentCost.json',
    addressSpacePointerAbi: '../../ZapContracts/build/contracts/AddressSpacePointer.json',
    addressSpace: '../../ZapContracts/build/contracts/AddressSpace.json'
};
